import 'story.dart';
import 'feed.dart';

List<Story> profiles = [
  Story(username: 'Your Story', profile: 'dm.jpg', isPressed: false),
  Story(username: 'zendaya', profile: 'zendaya.jpg', isPressed: false),
  Story(username: 'kyrieirving', profile: 'kyrie.jpg', isPressed: false),
  Story(username: 'travisscott', profile: 'travis.jpg', isPressed: false),
  Story(username: 'therock', profile: 'therock.jpeg', isPressed: false),
  Story(username: 'kyliejenner', profile: 'kylie.jpg', isPressed: false),
  Story(username: 'zendaya', profile: 'zendaya.jpg', isPressed: false),
  Story(username: 'kyrieirving', profile: 'kyrie.jpg', isPressed: false),
  Story(username: 'travisscott', profile: 'travis.jpg', isPressed: false),
  Story(username: 'therock', profile: 'therock.jpeg', isPressed: false),
  Story(username: 'kyliejenner', profile: 'kylie.jpg', isPressed: false),
];

List<Feed> posts = [
  Feed(
      username: 'zendaya',
      caption: 'sunday funday',
      post: 'zendaya_post.jpg',
      profile: 'zendaya.jpg',
      isLiked: false,
      isSaved: false,
      comments: 213,
      likes: 26000,
      posted: 73),
  Feed(
      username: 'travisscott',
      caption: 'sicko mode on',
      post: 'travis_post.jpeg',
      profile: 'travis.jpg',
      isLiked: false,
      isSaved: false,
      comments: 76,
      likes: 15000,
      posted: 96),
  Feed(
      username: 'therock',
      caption: 'workin\' hard',
      post: 'therock_post.jpeg',
      profile: 'therock.jpeg',
      isLiked: false,
      isSaved: false,
      comments: 100,
      likes: 18000,
      posted: 25),
  Feed(
      username: 'damjanzimbakov',
      caption: 'rock - art',
      post: 'dm_post.jpg',
      profile: 'zendaya.jpg',
      isLiked: false,
      isSaved: false,
      comments: 50,
      likes: 500,
      posted: 110),
  Feed(
      username: 'kyliejenner',
      caption: 'glossy.',
      post: 'kylie_post.jpg',
      profile: 'kylie.jpg',
      isLiked: false,
      isSaved: false,
      comments: 200,
      likes: 22234,
      posted: 49),
  Feed(
      username: 'zendaya',
      caption: 'sunday funday',
      post: 'zendaya_post.jpg',
      profile: 'zendaya.jpg',
      isLiked: false,
      isSaved: false,
      comments: 213,
      likes: 26000,
      posted: 73),
  Feed(
      username: 'travisscott',
      caption: 'sicko mode on',
      post: 'travis_post.jpg',
      profile: 'travis.jpg',
      isLiked: false,
      isSaved: false,
      comments: 76,
      likes: 15000,
      posted: 96),
  Feed(
      username: 'therock',
      caption: 'workin\' hard',
      post: 'therock_post.jpeg',
      profile: 'therock.jpeg',
      isLiked: false,
      isSaved: false,
      comments: 100,
      likes: 18000,
      posted: 25),
  Feed(
      username: 'damjanzimbakov',
      caption: 'rock - art',
      post: 'dm_post.jpg',
      profile: 'zendaya.jpg',
      isLiked: false,
      isSaved: false,
      comments: 50,
      likes: 500,
      posted: 110),
  Feed(
      username: 'kyliejenner',
      caption: 'glossy.',
      post: 'kylie_post.jpg',
      profile: 'kylie.jpg',
      isLiked: false,
      isSaved: false,
      comments: 200,
      likes: 22234,
      posted: 49),
];
